version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-enterprise
    container_name: docxp-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/docxp-neo4j-2024
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    networks:
      - docxp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7474/browser/"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: docxp-backend
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-anthropic.claude-v2}
      - DATABASE_URL=sqlite+aiosqlite:///./docxp.db
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=docxp-neo4j-2024
      - NEO4J_DATABASE=neo4j
    volumes:
      - ./backend/output:/app/output
      - ./backend/temp:/app/temp
      - ./backend/configs:/app/configs
      - backend-db:/app
    networks:
      - docxp-network
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: docxp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - docxp-network
    restart: unless-stopped

networks:
  docxp-network:
    driver: bridge

volumes:
  backend-db:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:
